name: Kokos build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install build-essential gcc meson pkg-config

    - name: Setup
      run: cd kokos && mkdir build && meson setup build

    - name: Compile
      run: cd kokos/build && meson compile
